redis.servers: 'redis://localhost:6379/0'
server.port: 23500
loglevel: 'INFO'

notifications.mail.on: true
notifications.mail.tls: false
notifications.mail.host: 'localhost'
notifications.mail.port: 25
notifications.mail.sender: 'zmon@example.com'

notifications.sms.on: true
notifications.sms.provider_url: 'https://gateway.smstrade.de'
notifications.sms.apikey: '--secret--'
notifications.sms.sender: 'zmon'
notifications.sms.route: 'gold'
notifications.sms.contact_groups: {'1stlevel': []}
notifications.sms.maxlength: 2048

zmon.queues: "zmon:queue:default/16,zmon:queue:internal/2"
safe_repositories: []

kairosdb.enabled: True
kairosdb.host: 'localhost'
kairosdb.port: 8083


metriccache.url: 'http://localhost:8086'
metriccache.check.id: 0
metriccache.check.ids: []

## plugin configuration: these values override those set in local plugin config files

plugin.eventlog.eventlog_url: 'https://eventlog.example.com/'

plugin.history.url: 'http://localhost:8083'

plugin.kairosdb.url: 'http://localhost:8083'

plugin.joblocks.cmdb_url: 'https://cmdb.example.com/'

plugin.ldap.user: 'user'
plugin.ldap.pass: '--secret--'

plugin.sql.user: 'zmon'
plugin.sql.pass: '--secret--'

plugin.orasql.user: 'zmon'
plugin.orasql.pass: '--secret--'

plugin.mysql.user: 'zmon'
plugin.mysql.pass: '--secret--'

plugin.mssql.user: 'zmon'
plugin.mssql.pass: '--secret--'

plugin.elasticsearch.url: 'https://es-cluster'

plugin.appdynamics.url: 'https://appdynamics'

plugin.saml.url: 'https://idp.example.com/profile/SAML2/Unsolicited/SSO?providerId=urn:self'
plugin.openam.url: 'https://auth.zalando.com/z'
